---
title: "PCA EFA: DARWIN"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

# DARWIN Univariate

### Loading the libraries

```{r}
library("FRESA.CAD")
library(psych)

library(readxl)
op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```



## The Data

```{r}
DARWIN <- read.csv("~/GitHub/FCA/Data/DARWIN/DARWIN.csv")
rownames(DARWIN) <- DARWIN$ID
DARWIN$ID <- NULL
DARWIN$class <- 1*(DARWIN$class=="P")
print(table(DARWIN$class))

DARWIN[,1:ncol(DARWIN)] <- sapply(DARWIN,as.numeric)

#signedlog <- function(x) { return (sign(x)*log(abs(1.0e12*x)+1.0))}
#whof <- !(colnames(DARWIN) %in% c("class"));
#DARWIN[,whof] <- signedlog(DARWIN[,whof])



```


#### Standarize the names for the reporting

```{r results = "asis"}
dataframe <- DARWIN
outcome <- "class"

trainFraction <- 0.5
rhoThreshold <- 0.5
TopVariables <- 10

trainSample <- sample(nrow(dataframe),nrow(dataframe)*trainFraction)

trainDataFrame <- dataframe[trainSample,]
testDataFrame <- dataframe[-trainSample,]

```



```{r results = "asis"}
pander::pander(c(rows=nrow(dataframe),col=ncol(dataframe)-1))
pander::pander(table(dataframe[,outcome]))

varlist <- colnames(dataframe)
varlist <- varlist[varlist != outcome]
varlist <- as.data.frame(cbind(name=varlist,desc=varlist))

```


## Univariate

```{r results = "asis"}

univariate_columns <- c("caseMean","caseStd","controlMean","controlStd","controlKSP","ROCAUC","wilcox.Zvalue")
univar <- uniRankVar(varlist,
	           paste(outcome,"~1"),
	           outcome,
	           testDataFrame,
              rankingTest = "AUC")



```

## Decorrelation with GDSTM Blind

```{r results = "asis"}
DEdataframe <- GDSTMDecorrelation(trainDataFrame,thr=rhoThreshold)
varlistDe <-  colnames(DEdataframe)[colnames(DEdataframe) != outcome];
varlistDe <- as.data.frame(cbind(name=varlistDe,desc=varlistDe))

pander::pander(head(getLatentCoefficients(DEdataframe)))
predTestDe <- predictDecorrelate(DEdataframe,testDataFrame)

univarDe <- uniRankVar(varlistDe,
              paste(outcome,"~1"),
	            outcome,
              predTestDe,
              rankingTest = "AUC")


```

## Decorrelation with GDSTM Driven

```{r results = "asis"}

DriDEdataframe <- GDSTMDecorrelation(trainDataFrame,Outcome=outcome,thr=rhoThreshold)
varlistDe <-  colnames(DriDEdataframe)[colnames(DriDEdataframe) != outcome];
varlistDe <- as.data.frame(cbind(name=varlistDe,desc=varlistDe))

pander::pander(head(getLatentCoefficients(DriDEdataframe)))
predTestDri <- predictDecorrelate(DriDEdataframe,testDataFrame)

univarDeDri <- uniRankVar(varlistDe,
              paste(outcome,"~1"),
	            outcome,
              predTestDri,
              rankingTest = "AUC")


```


## PCA Analysis

```{r results = "asis"}

### PCA 
noclassData <- trainDataFrame[,colnames(trainDataFrame) != outcome]
noclassTestData <- testDataFrame[,colnames(testDataFrame) != outcome]
pc <- principal(noclassData,TopVariables,rotate="varimax")   #principal components
pander::pander(head(pc$loadings))
PCA_Train <- as.data.frame(cbind(predict(pc,noclassData),trainDataFrame[,outcome]))
colnames(PCA_Train)[TopVariables+1] <- outcome

PCA_Predicted <- as.data.frame(cbind(predict(pc,noclassTestData),testDataFrame[,outcome]))
colnames(PCA_Predicted)[TopVariables+1] <- outcome
varlistPCA <-  colnames(PCA_Predicted)[colnames(PCA_Predicted) != "class"];
varlistPCA <- as.data.frame(cbind(name=varlistPCA,desc=varlistPCA))

univarPCA <- uniRankVar(varlistPCA,
              paste(outcome,"~1"),
	            outcome,
              PCA_Predicted)



```

## EFA
```{r results = "asis"}

uls <- fa(noclassData,TopVariables,rotate="varimax")  #unweighted least squares is minres 
pander::pander(head(uls$weights)) 
EFA_Train <- as.data.frame(cbind(predict(uls,noclassData),trainDataFrame[,outcome]))
colnames(EFA_Train)[TopVariables+1] <- outcome
EFA_Predicted <- as.data.frame(cbind(predict(uls,noclassTestData),testDataFrame[,outcome]))
colnames(EFA_Predicted)[TopVariables+1] <- outcome
varlistEFA <-  colnames(EFA_Predicted)[colnames(EFA_Predicted) != "class"];
varlistEFA <- as.data.frame(cbind(name=varlistEFA,desc=varlistEFA))

univarEFA <- uniRankVar(varlistEFA,
              paste(outcome,"~1"),
	            outcome,
              EFA_Predicted)


```

### The tables

```{r results = "asis"}
pander::pander(univar$orderframe[1:TopVariables,univariate_columns])
pander::pander(univarDe$orderframe[1:TopVariables,univariate_columns])
pander::pander(univarDeDri$orderframe[1:TopVariables,univariate_columns])
pander::pander(univarPCA$orderframe[1:TopVariables,univariate_columns])
pander::pander(univarEFA$orderframe[1:TopVariables,univariate_columns])

```

### Model of top five variables

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 5.0, fig.width= 5.0}

lmRAW <- glm(paste(outcome,"~."),
             trainDataFrame[,c(outcome,rownames(univar$orderframe[1:TopVariables,]))],
             family="binomial")
pr <- predictionStats_binary(cbind(testDataFrame[,outcome],predict(lmRAW,testDataFrame)),"Top Raw",cex=0.95)

lmDe <- glm(paste(outcome,"~."),
            DEdataframe[,c(outcome,rownames(univarDe$orderframe[1:TopVariables,]))],
            family="binomial")
pr <- predictionStats_binary(cbind(predTestDe[,outcome],predict(lmDe,predTestDe)),"Top Blind:GDSTM",cex=0.95)

lmDri <- glm(paste(outcome,"~."),
            DriDEdataframe[,c(outcome,rownames(univarDeDri$orderframe[1:TopVariables,]))],
            family="binomial")
pr <- predictionStats_binary(cbind(predTestDe[,outcome],predict(lmDri,predTestDri)),"Top Driven:GDSTM",cex=0.95)


lmPCA <- glm(paste(outcome,"~."),
            PCA_Train,
            family="binomial")
pr <- predictionStats_binary(cbind(PCA_Predicted[,outcome],predict(lmPCA,PCA_Predicted)),"Top PCA",cex=0.95)


lmEFA <- glm(paste(outcome,"~."),
            EFA_Train,
            family="binomial")
pr <- predictionStats_binary(cbind(EFA_Predicted[,outcome],predict(lmEFA,EFA_Predicted)),"Top EFA",cex=0.95)


```

