---
title: "TADPOLE_Survival"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

# TADPOLE Univariate

### The run options
```{r}
TrainFraction <- 0.50;
sig_pvalue <- 0.01
thr <- c(0.05,0.2,0.4,0.6,0.8,0.95);
method  <- c("fast","pearson","spearman","kendall");
type <- c("LM","RLM")
DeOutcome <- c("NoDriven","Driven")
corRankS <- c("FALSE","TRUE")

thr <- thr[4]
method  <- method[1]
type <- type[1] 
DeOutcome <- DeOutcome[2]
corRankS <- corRankS[2]


corRank <- corRankS == "TRUE"

```


### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library("whitening")
library("fpc")
library("robust")
op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```
## The data set

```{r}
TADPOLE_D1_D2 <- read.csv("~/GitHub/BSWiMS/Data/TADPOLE/TADPOLE_D1_D2.csv")
TADPOLE_D1_D2_Dict <- read.csv("~/GitHub/BSWiMS/Data/TADPOLE/TADPOLE_D1_D2_Dict.csv")
TADPOLE_D1_D2_Dict_LR <- as.data.frame(read_excel("~/GitHub/BSWiMS/Data/TADPOLE/TADPOLE_D1_D2_Dict_LR.xlsx",sheet = "LeftRightFeatures"))


rownames(TADPOLE_D1_D2_Dict) <- TADPOLE_D1_D2_Dict$FLDNAME

```

## Conditioning the data

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

# mm3 to mm
isVolume <- c("Ventricles","Hippocampus","WholeBrain","Entorhinal","Fusiform","MidTemp","ICV",
              TADPOLE_D1_D2_Dict$FLDNAME[str_detect(TADPOLE_D1_D2_Dict$TEXT,"Volume")]
              )


#TADPOLE_D1_D2[,isVolume] <- apply(TADPOLE_D1_D2[,isVolume],2,'^',(1/3))
TADPOLE_D1_D2[,isVolume] <- TADPOLE_D1_D2[,isVolume]^(1/3)

# mm2 to mm
isArea <- TADPOLE_D1_D2_Dict$FLDNAME[str_detect(TADPOLE_D1_D2_Dict$TEXT,"Area")]
TADPOLE_D1_D2[,isArea] <- sqrt(TADPOLE_D1_D2[,isArea])

# Get only cross sectional measurements
FreeSurfersetCross <- str_detect(colnames(TADPOLE_D1_D2),"UCSFFSX")

# The subset of baseline measurements
baselineTadpole <- subset(TADPOLE_D1_D2,VISCODE=="bl")
table(baselineTadpole$DX)
table(baselineTadpole$DX_bl)

rownames(baselineTadpole) <- baselineTadpole$PTID


validBaselineTadpole <- cbind(DX=baselineTadpole$DX_bl,
                                 AGE=baselineTadpole$AGE,
                                 Gender=1*(baselineTadpole$PTGENDER=="Female"),
                                 ADAS11=baselineTadpole$ADAS11,
                                 ADAS13=baselineTadpole$ADAS13,
                                 MMSE=baselineTadpole$MMSE,
                                 RAVLT_immediate=baselineTadpole$RAVLT_immediate,
                                 RAVLT_learning=baselineTadpole$RAVLT_learning,
                                 RAVLT_forgetting=baselineTadpole$RAVLT_forgetting,
                                 RAVLT_perc_forgetting=baselineTadpole$RAVLT_perc_forgetting,
                                 FAQ=baselineTadpole$FAQ,
                                 Ventricles=baselineTadpole$Ventricles,
                                 Hippocampus=baselineTadpole$Hippocampus,
                                 WholeBrain=baselineTadpole$WholeBrain,
                                 Entorhinal=baselineTadpole$Entorhinal,
                                 Fusiform=baselineTadpole$Fusiform,
                                 MidTemp=baselineTadpole$MidTemp,
                                 ICV=baselineTadpole$ICV,
                                 baselineTadpole[,FreeSurfersetCross])


LeftFields <- TADPOLE_D1_D2_Dict_LR$LFN
names(LeftFields) <- LeftFields
LeftFields <- LeftFields[LeftFields %in% colnames(validBaselineTadpole)]
RightFields <- TADPOLE_D1_D2_Dict_LR$RFN
names(RightFields) <- RightFields
RightFields <- RightFields[RightFields %in% colnames(validBaselineTadpole)]

## Normalize to ICV
validBaselineTadpole$Ventricles=validBaselineTadpole$Ventricles/validBaselineTadpole$ICV
validBaselineTadpole$Hippocampus=validBaselineTadpole$Hippocampus/validBaselineTadpole$ICV
validBaselineTadpole$WholeBrain=validBaselineTadpole$WholeBrain/validBaselineTadpole$ICV
validBaselineTadpole$Entorhinal=validBaselineTadpole$Entorhinal/validBaselineTadpole$ICV
validBaselineTadpole$Fusiform=validBaselineTadpole$Fusiform/validBaselineTadpole$ICV
validBaselineTadpole$MidTemp=validBaselineTadpole$MidTemp/validBaselineTadpole$ICV

leftData <- validBaselineTadpole[,LeftFields]/validBaselineTadpole$ICV
RightData <- validBaselineTadpole[,RightFields]/validBaselineTadpole$ICV

## get mean and relative difference 
meanLeftRight <- (leftData + RightData)/2
difLeftRight <- abs(leftData - RightData)
reldifLeftRight <- difLeftRight/meanLeftRight
colnames(meanLeftRight) <- paste("M",colnames(meanLeftRight),sep="_")
colnames(difLeftRight) <- paste("D",colnames(difLeftRight),sep="_")
colnames(reldifLeftRight) <- paste("RD",colnames(reldifLeftRight),sep="_")


validBaselineTadpole <- validBaselineTadpole[,!(colnames(validBaselineTadpole) %in% 
                                               c(LeftFields,RightFields))]
#validBaselineTadpole <- cbind(validBaselineTadpole,meanLeftRight,difLeftRight,reldifLeftRight)
validBaselineTadpole <- cbind(validBaselineTadpole,meanLeftRight,difLeftRight)

## Remove columns with too many NA more than %15 of NA
nacount <- apply(is.na(validBaselineTadpole),2,sum)/nrow(validBaselineTadpole) < 0.15
diagnose <- validBaselineTadpole$DX
pander::pander(table(diagnose))
validBaselineTadpole <- validBaselineTadpole[,nacount]
## Remove character columns
ischar <- sapply(validBaselineTadpole,class) == "character"
validBaselineTadpole <- validBaselineTadpole[,!ischar]
## Place back diagnose
validBaselineTadpole$DX <- diagnose


validBaselineTadpole <- validBaselineTadpole[complete.cases(validBaselineTadpole),]
ischar <- sapply(validBaselineTadpole,class) == "character"
validBaselineTadpole[,!ischar] <- sapply(validBaselineTadpole[,!ischar],as.numeric)

colnames(validBaselineTadpole) <- str_remove_all(colnames(validBaselineTadpole),"_UCSFFSX_11_02_15_UCSFFSX51_08_01_16")
colnames(validBaselineTadpole) <- str_replace_all(colnames(validBaselineTadpole)," ","_")
validBaselineTadpole$LONISID <- NULL
validBaselineTadpole$IMAGEUID <- NULL
validBaselineTadpole$LONIUID <- NULL

diagnose <- as.character(validBaselineTadpole$DX)
validBaselineTadpole$DX <- diagnose
pander::pander(table(validBaselineTadpole$DX))


validBaselineTadpole[validBaselineTadpole$DX %in% c("EMCI","LMCI"),"DX"] <- "MCI" 
validBaselineTadpole[validBaselineTadpole$DX %in% c("CN","SMC"),"DX"] <- "NL" 

pander::pander(table(validBaselineTadpole$DX))



```

## Get the Time To Event on MCI Subjects

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

subjectsID <- rownames(validBaselineTadpole)
visitsID <- unique(TADPOLE_D1_D2$VISCODE)
baseDx <- TADPOLE_D1_D2[TADPOLE_D1_D2$VISCODE=="bl",c("PTID","DX","EXAMDATE")]
rownames(baseDx) <- baseDx$PTID 
baseDx <- baseDx[subjectsID,]
lastDx <- baseDx
toDementia <- baseDx
table(lastDx$DX)
hasDementia <- lastDx$PTID[str_detect(lastDx$DX,"Dementia")]


for (vid in visitsID)
{
  DxValue <- TADPOLE_D1_D2[TADPOLE_D1_D2$VISCODE==vid,c("PTID","DX","EXAMDATE")]
  rownames(DxValue) <- DxValue$PTID 
  DxValue <- DxValue[DxValue$PTID %in% subjectsID,]
  noDX <- DxValue$PTID[nchar(DxValue$DX) < 1]
  print(length(noDX))
  DxValue[noDX,] <- lastDx[noDX,]
  inLast <- lastDx$PTID[lastDx$PTID %in% DxValue$PTID]
  print(length(inLast))
  lastDx[inLast,] <- DxValue[inLast,]
  noDementia <- !(toDementia$PTID %in% hasDementia)
  toDementia[noDementia,] <- lastDx[noDementia,]
  hasDementia <- unique(c(hasDementia,lastDx$PTID[str_detect(lastDx$DX,"Dementia")]))
}
table(lastDx$DX)
baseMCI <-baseDx$PTID[baseDx$DX == "MCI"]
lastDementia <- lastDx$PTID[str_detect(lastDx$DX,"Dementia")]
lastDementia2 <- toDementia$PTID[str_detect(toDementia$DX,"Dementia")]
lastNL <- lastDx$PTID[str_detect(lastDx$DX,"NL")]

MCIatBaseline <- baseDx[baseMCI,]
MCIatEvent <- toDementia[baseMCI,]
MCIatLast <- lastDx[baseMCI,]

MCIconverters <- MCIatBaseline[baseMCI %in% lastDementia,]
MCI_No_converters <- MCIatBaseline[!(baseMCI %in% MCIconverters$PTID),]
MCIconverters$TimeToEvent <- (as.Date(toDementia[MCIconverters$PTID,"EXAMDATE"]) 
                                   - as.Date(MCIconverters$EXAMDATE))

sum(MCIconverters$TimeToEvent ==0)


MCIconverters$AtEventDX <- MCIatEvent[MCIconverters$PTID,"DX"]
MCIconverters$LastDX <- MCIatLast[MCIconverters$PTID,"DX"]

MCI_No_converters$TimeToEvent <- (as.Date(lastDx[MCI_No_converters$PTID,"EXAMDATE"]) 
                                   - as.Date(MCI_No_converters$EXAMDATE))

MCI_No_converters$LastDX <- MCIatLast[MCI_No_converters$PTID,"DX"]

MCI_No_converters <- subset(MCI_No_converters,TimeToEvent > 0)



```


# Prognosis MCI to AD Conversion

## the set
```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

MCIPrognosisIDs <- c(MCIconverters$PTID,MCI_No_converters$PTID)

TADPOLECrossMRI <- validBaselineTadpole[MCIPrognosisIDs,]
table(TADPOLECrossMRI$DX)
TADPOLECrossMRI$DX <- NULL
TADPOLECrossMRI$status <- 1*(rownames(TADPOLECrossMRI) %in% MCIconverters$PTID)
table(TADPOLECrossMRI$status)

```



#### Analysis parameters

```{r results = "asis"}
dataframe <- TADPOLECrossMRI
outcome <- "status"



```


```{r results = "asis"}
pander::pander(c(rows=nrow(dataframe),col=ncol(dataframe)-1))
pander::pander(table(dataframe[,outcome]))

varlist <- colnames(dataframe)
varlist <- varlist[varlist != outcome]
varlist <- as.data.frame(cbind(name=varlist,desc=varlist))

```


## Univariate

```{r results = "asis"}

univariate_columns <- c("caseMean","caseStd","controlMean","controlStd","controlKSP","ROCAUC","WilcoxRes.p","FRes.p")
univar <- uniRankVar(varlist,
	           paste(outcome,"~1"),
	           outcome,
	           dataframe,
	           categorizationType = "Raw",
	           type = "LOGIT",
	           rankingTest = "AUC",
	            cateGroups = c(0.1, 0.9),
	            raw.dataFrame = NULL,
	            description = ".",
	            uniType = "Binary")

pander::pander(univar$orderframe[1:20,univariate_columns])

topfiveOrg <- rownames(univar$orderframe[1:5,])

```

## Decorrelation Analysis

```{r results = "asis"}
DEdataframe <- GDSTMDecorrelation(dataframe,thr=0.80,verbose = TRUE)

pander::pander(c(Decorrleated_Fraction=sum(str_detect(colnames(DEdataframe),"La_"))/(ncol(DEdataframe)-1)))
pander::pander(c(Base_Fraction=sum(str_detect(colnames(DEdataframe),"Ba_"))/(ncol(DEdataframe)-1)))
demat <- attr(DEdataframe,"GDSTM")
pander::pander(c(sparse_Fraction=1.0-sum(demat==0)/ncol(demat)/nrow(demat)))
varlistDe <-  colnames(DEdataframe)[colnames(DEdataframe) != "class"];
varlistDe <- as.data.frame(cbind(name=varlistDe,desc=varlistDe))



```

### The heat maps.

```{r results = "asis", warning = FALSE, dpi=300, fig.height= 5.0, fig.width= 7.0}

par(cex=0.6,cex.main=0.85,cex.axis=0.7)
cormat <- cor(dataframe[,rownames(demat)],method="spearman")
cormat[is.na(cormat)] <- 0
gplots::heatmap.2(abs(cormat),
                  trace = "none",
#                  scale = "row",
                  mar = c(5,5),
                  col=rev(heat.colors(5)),
                  main = "Spearman Correlation Original",
                  cexRow = 0.35,
                  cexCol = 0.35,
                  key.title=NA,
                  key.xlab="Spearman Correlation",
                  xlab="Feature", ylab="Feature")


cormat <- cor(DEdataframe[,colnames(demat)],method="spearman")
cormat[is.na(cormat)] <- 0
gplots::heatmap.2(abs(cormat),
                  trace = "none",
#                  scale = "none",
                  mar = c(5,5),
                  col=rev(heat.colors(5)),
                  main = "Spearman Correlation: After GDSTM",
                  cexRow = 0.35,
                  cexCol = 0.35,
                  key.title=NA,
                  key.xlab="Spearman Correlation",
                  xlab="Feature", ylab="Feature")

par(op)
```


## Univariate Decorrelated

```{r results = "asis"}

univarDe <- uniRankVar(varlistDe,
              paste(outcome,"~1"),
	            outcome,
              DEdataframe,
	            categorizationType = "Raw",
	            type = "LOGIT",
	            rankingTest = "AUC",
	            cateGroups = c(0.1, 0.9),
	            raw.dataFrame = NULL,
	            description = ".",
	            uniType = "Binary")

pander::pander(univarDe$orderframe[1:20,univariate_columns])

```

### Comparing Decorrelation vs Original

```{r results = "asis"}
pthr <- 0.20/(ncol(dataframe)-1)

topDecorNames <- rownames(univarDe$orderframe[univarDe$orderframe$FRes.p<pthr,])
topDecorNames <- unique(c(topDecorNames,rownames(univarDe$orderframe[1:5,])))

#topDecorNames <- rownames(univarDe$orderframe[univarDe$orderframe$FRes.p<1.0e-5,])
dc <- getLatentCoefficients(DEdataframe)
### 2a Get only the ones that in the top features
deNames_in_dc <- topDecorNames[topDecorNames %in% names(dc)]
selectedlist <- dc[deNames_in_dc]
theDeFormulas <- selectedlist

rawuniv <- univariate_Wilcoxon(dataframe,outcome,limit=-1)
deuniv <- univariate_Wilcoxon(DEdataframe,outcome,limit=-1)
matsize <- (ncol(dataframe)-1)^2
nocorrelated <- ncol(dataframe) - 1 - ncol(demat)
pander::pander(c(sparse_Fraction=(sum(demat != 0) + nocorrelated)/matsize))
pander::pander(c(raw=length(rawuniv),decor=length(deuniv)))
pander::pander(c(Number_Latent=length(dc)))
pander::pander(c(meanSize=mean(sapply(dc,length))))


```


## CV ROC Analysis

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 4.0, fig.width= 8.0}
par(op)
par(mfrow=c(1,2),cex=0.9)
fraction <-0.80
repetitions <- 100

fcout <- round(fraction*nrow(dataframe)/15+1.0)
pander::pander(c(NumberofFeatures=fcout))

cvRaw <- randomCV(dataframe,
                outcome,
                fittingFunction= filteredFit,
                classSamplingType = "Pro",
                trainFraction = fraction,
                repetitions = repetitions,
#                fitmethod=  glm,
                fitmethod=  KNN_method,
                filtermethod=mRMR.classic_FRESA,
                filtermethod.control=list(feature_count= fcout),
#                family="binomial"
)
bpraw <- predictionStats_binary(cvRaw$medianTest,"RAW",cex=0.75)


pander::pander(bpraw$CM.analysis$tab)
pander::pander(bpraw$accc)
pander::pander(bpraw$aucs)
pander::pander(bpraw$berror)

cvDe <- randomCV(DEdataframe,
                outcome,
                fittingFunction= filteredFit,
                trainSampleSets= cvRaw$trainSamplesSets,
#                fitmethod=  glm,
                fitmethod=  KNN_method,
                filtermethod=mRMR.classic_FRESA,
                filtermethod.control=list(feature_count= fcout),
#                family="binomial"
)
bpDecor <- predictionStats_binary(cvDe$medianTest,"Decorrelated",cex=0.75)

par(op)

pander::pander(bpDecor$CM.analysis$tab)
pander::pander(bpDecor$accc)
pander::pander(bpDecor$aucs)
pander::pander(bpDecor$berror)

### Here we compute the probability that the outcome-driven decorrelation ROC is superior to the RAW ROC. 
pander::pander(roc.test(bpDecor$ROC.analysis$roc.predictor,bpraw$ROC.analysis$roc.predictor,alternative = "greater"))


```

## Feature Frequency Plots
```{r results = "asis", warning = FALSE, dpi=300, fig.height= 6.0, fig.width= 6.0}
par(mfrow=c(2,1),cex=0.9,cex.axis=0.8)

rawtopf <- cvRaw$featureFrequency/repetitions
crawtopf <- rawtopf

if (length(rawtopf) > 30)
{
  rawtopf <- rawtopf[1:30]
}
barplot(100*rawtopf,las=2,main="Raw Features",ylim=c(0,100.0),cex.names = 0.35,cex.axis = 0.35,ylab="Sel. %")

detopf <- cvDe$featureFrequency/repetitions
cdetopf <- detopf
names(cdetopf) <- str_remove_all(names(cdetopf),"Ba_")
names(cdetopf) <- str_remove_all(names(cdetopf),"La_")
if (length(detopf) > 30)
{
  detopf <- detopf[1:30]
}

barplot(100*detopf,las=2,main="Decorrelated Features",ylim=c(0,100.0),cex.names = 0.35,cex.axis = 0.35,ylab="Sel. %")

par(op)



```



### Final Table

```{r results = "asis"}
unlistdecorr <- selectedlist
names(unlistdecorr) <- NULL
unlistdecorr <- unique(names(unlist(unlistdecorr)))

finalTableDe <- univarDe$orderframe[deNames_in_dc,univariate_columns]

finalTableOr <- univar$orderframe[unique(c(topfiveOrg,unlistdecorr,names(crawtopf)[1:2],names(cdetopf)[1:2])),univariate_columns]

finalTable <- rbind(finalTableOr,finalTableDe)

deFromula <- character(length(theDeFormulas))
names(deFromula) <- names(theDeFormulas)

for (dx in names(deFromula))
{
  coef <- theDeFormulas[[dx]]
  cname <- names(theDeFormulas[[dx]])
  names(cname) <- cname
  for (cf in names(coef))
  {
    if (cf != dx)
    {
      if (coef[cf]>0)
      {
        deFromula[dx] <- paste(deFromula[dx],
                               sprintf("+ %5.3f*%s",coef[cf],cname[cf]))
      }
      else
      {
        deFromula[dx] <- paste(deFromula[dx],
                               sprintf("%5.3f*%s",coef[cf],cname[cf]))
      }
    }
  }
}

orgnamez <- rownames(finalTable)
orgnamez <- str_remove_all(orgnamez,"Ba_")
orgnamez <- str_remove_all(orgnamez,"La_")
finalTable$uAUC <- univar$orderframe[orgnamez,"ROCAUC"]
finalTable$raw_Freq <- crawtopf[orgnamez]
finalTable$La_Freq <- cdetopf[orgnamez]
finalTable$DecorFormula <- deFromula[rownames(finalTable)]
fscores <- attr(DEdataframe,"fscore")
finalTable$fscores <- fscores[rownames(finalTable)]

finalTable <- finalTable[order(-finalTable$ROCAUC),]

pander::pander(finalTable)
```

