---
title: "Decorrelation-Based SOTA: Diabetes"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")

```

# Effect of UPSTM-Based Decorrelation on ML Performance


### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
library(umap)
library(tsne)
library(entropy)
library(mlbench)

op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)
source("C:/Users/jtame/Documents/GitHub/LatentBiomarkers/RMD/DecorrelationCV.R")

```


## Material and Methods

mlBench library

Newman, D.J. & Hettich, S. & Blake, C.L. & Merz, C.J. (1998). UCI Repository of machine learning databases [http://www.ics.uci.edu/~mlearn/MLRepository.html]. Irvine, CA: University of California, Department of Information and Computer Science.

## The Data

```{r}
data("PimaIndiansDiabetes2", package = "mlbench")
PimaIndiansDiabetes  <- PimaIndiansDiabetes2[complete.cases(PimaIndiansDiabetes2),]


#data(PimaIndiansDiabetes)
#PimaIndiansDiabetes  <- PimaIndiansDiabetes[complete.cases(PimaIndiansDiabetes),]


PimaIndiansDiabetes_mat <- as.data.frame(model.matrix(diabetes~.*.,PimaIndiansDiabetes)[,-1])
fnames <- colnames(PimaIndiansDiabetes_mat)
fnames <- str_replace_all(fnames," ","_")
fnames <- str_replace_all(fnames,"/","_")
fnames <- str_replace_all(fnames,":","_x_")
colnames(PimaIndiansDiabetes_mat) <- fnames

whohasx <- str_detect(fnames,"_x_")
PimaIndiansDiabetes_mat[,whohasx] <- sqrt(PimaIndiansDiabetes_mat[,whohasx])

pander::pander(table(PimaIndiansDiabetes$diabetes))
PimaIndiansDiabetes_mat$diabetes <- 1*(PimaIndiansDiabetes$diabetes=="pos")

```



#### Standarize the names for the reporting

```{r results = "asis"}
studyName <- "Diabetes"
dataframe <- PimaIndiansDiabetes_mat
outcome <- "diabetes"


nLoops <- 100

needScaling <- TRUE
IDSample <- FALSE
thro <- 0.8

```

## CV Analysis and report

```{r parent, child = here::here("~/GitHub/LatentBiomarkers/RMD/Child_univariate/SOTACV_analysis.Rmd")}
```


