---
output: html_document
editor_options: 
  chunk_output_type: console
---
### Libraries
Some libraries
```{r}
library("pls")

```

### CV interface

```{r}

plfit <- function(formula=formula,data=NULL,...)
{
  fitpls <- plsr(formula=formula,data=data,scale =TRUE,...)
  class(fitpls) <- c("TopPLS",class(fitpls))
  return(fitpls)
}

pcrfit <- function(formula=formula,data=NULL,...)
{
  fitpls <- pcr(formula=formula,data=data,scale =TRUE,...)
  class(fitpls) <- c("TopPLS",class(fitpls))
  return(fitpls)
}

cpplsfit <- function(formula=formula,data=NULL,...)
{
  fitpls <- cppls(formula=formula,data=data,scale =TRUE,...)
  class(fitpls) <- c("TopPLS",class(fitpls))
  return(fitpls)
}

predict.TopPLS <- function(object,...)
{
  parameters <- list(...);
	testData <- parameters[[1]];
	class(object) <- class(object)[2]
  pred <- predict(object,newdata=testData)
  return(pred[,1,object$ncomp])
}


```

## PLSR vs ILAA

```{r, results = "asis", warning = FALSE, dpi=300, fig.height= 4.5, fig.width= 6.0}

toPCA <- sapply(apply(dataframe,2,unique),length) >= 5 & colnames(dataframe) != outcome

pc <- prcomp(dataframe[,toPCA],center = TRUE,scale. = TRUE,tol=0.01)   #principal components

if (ncol(dataframe)<20)
{
pander::pander(as.data.frame(pc$rotation),caption="PCA")
}

rotstd <- log10(abs(100*pc$rotation)+1.0)
  gplots::heatmap.2(rotstd,
                    trace = "none",
                    dendrogram="none",
                    breaks=c(0,0.5,1,2,3),
#                    scale="row",
                    mar = c(5,5),
                    col=rainbow(4),
                    main = "PCA Rotation",
                    cexRow = cexheat,
                    cexCol = cexheat,
                    Rowv=FALSE,
                    Colv=FALSE,
                   srtCol=45,
                   srtRow=45,
                    key.title=NA,
                    key.xlab="log(|100Rot|+1)",
                    xlab="Output Feature", ylab="Input Feature")


efa <- try(fa(dataframe[,toPCA],ncol(pc$rotation),rotate="varimax",warnings=FALSE))  # EFA analysis

if (!inherits(efa,"try-error"))
{
  if (ncol(dataframe)<20)
  {
   pander::pander(as.data.frame(efa$weights),caption="EFA")
  rotstd <- log10(abs(100*efa$weights)+1.0)
    gplots::heatmap.2(rotstd,
                      trace = "none",
                      dendrogram="none",
                      breaks=c(0,0.5,1,2,3),
  #                    scale="row",
                      mar = c(5,5),
                      col=rainbow(4),
                      main = "EFA weights",
                      cexRow = cexheat,
                      cexCol = cexheat,
                      Rowv=FALSE,
                      Colv=FALSE,
                     srtCol=45,
                     srtRow=45,
                      key.title=NA,
                      key.xlab="log(|100W|+1)",
                      xlab="Output Feature", ylab="Input Feature")
  }
}

  
  
plm <- plsr(formula=formula(paste(outcome,"~.")),data=dataframe,scale =TRUE)
if (ncol(dataframe)<20)
{
  lds <- plm$loadings
  lds2 <- matrix(as.numeric(lds),nrow=nrow(lds),ncol=ncol(lds))
  colnames(lds2) <- colnames(lds)
  rownames(lds2) <- rownames(lds)
  pander::pander(lds2,caption="PLS")
}

loadadings <- log10(abs(100*plm$loadings) + 1.0)
  gplots::heatmap.2(loadadings,
                    breaks=c(0,0.5,1,2,3),
                    trace = "none",
                    dendrogram="none",
#                    scale="row",
                    mar = c(5,5),
                    col=rainbow(4),
                    main = "PLS Loadings",
                    cexRow = cexheat,
                    cexCol = cexheat,
                    Rowv=FALSE,
                    Colv=FALSE,
                   srtCol=45,
                   srtRow=45,
                    key.title=NA,
                    key.xlab="log(|100Beta|+1)",
                    xlab="Output Feature", ylab="Input Feature")


ERTmod <- ILAA(dataframe,Outcome = outcome,thr=thro)

ERT <- log10(abs(100*attr(ERTmod,"UPLTM")) + 1);
  gplots::heatmap.2(ERT,
                    trace = "none",
                    breaks=c(0,0.5,1,2,3),
                    mar = c(5,5),
                    col=rainbow(4),
                    main = "ERT Loadings",
                    cexRow = cexheat,
                    cexCol = cexheat,
                    dendrogram="none",
                    Rowv=FALSE,
                    Colv=FALSE,
                   srtCol=45,
                   srtRow=45,
                    key.title=NA,
                    key.xlab="log(|100Beta|+1)",
                    xlab="Output Feature", ylab="Input Feature")

if (ncol(dataframe)<20)
{
pander::pander(attr(ERTmod,"UPLTM"),caption="ERT")
}


```



## SOTA Comparison to PLS, PC, LASSO, and ENET
### PLSR

```{r PLSR, results = "asis", warning = FALSE, dpi=300, fig.height= 4.5, fig.width= 6.0}


PLScv <- randomCV(dataframe,outcome,plfit,
                        trainFraction = tfrac,
                        repetitions = loops)

PLSbs <- predictionStats_regression(PLScv$medianTest,"PLS: CV")

```

### PC 

```{r PCR, results = "asis", warning = FALSE, dpi=300, fig.height= 4.5, fig.width= 6.0}


PCcv <- randomCV(fittingFunction = pcrfit,
                     trainSampleSets = PLScv$trainSamplesSets
                    )

PCbs <- predictionStats_regression(PCcv$medianTest,"PCR: CV")

```

### CPP

```{r CPP, results = "asis", warning = FALSE, dpi=300, fig.height= 4.5, fig.width= 6.0}


#CPPlcv <- randomCV(fittingFunction = cpplsfit,
#                     trainSampleSets = PLScv$trainSamplesSets
#                    )

#CPPlbs <- predictionStats_regression(CPPlcv$medianTest,"cppls: CV")

```


### LASSO

```{r LASSO, results = "asis", warning = FALSE, dpi=300, fig.height= 4.5, fig.width= 6.0}


LASSOcv <- randomCV(fittingFunction = LASSO_MIN,
                     trainSampleSets = PLScv$trainSamplesSets)

LASSObs <- predictionStats_regression(LASSOcv$medianTest,"LASSO: CV")



```

### PCA LASSO

```{r PCALASSO, results = "asis", warning = FALSE, dpi=300, fig.height= 4.5, fig.width= 6.0}


PCALASSOcv <- randomCV(fittingFunction = filteredFit,
                     trainSampleSets = PLScv$trainSamplesSets,
                     fitmethod = LASSO_MIN,
                      filtermethod = NULL,
                    PCA = TRUE)

PCALASSObs <- predictionStats_regression(PCALASSOcv$medianTest,"PCA-LASSO: CV")
```


### ILAA LASSO

```{r ILAALASSO, results = "asis", warning = FALSE, dpi=300, fig.height= 4.5, fig.width= 6.0}


ILAALASSOcv <- randomCV(fittingFunction = filteredFit,
                     trainSampleSets = PLScv$trainSamplesSets,
                     fitmethod = LASSO_MIN,
                      filtermethod = NULL,
                    DECOR = TRUE,
                    DECOR.control=list(thr=thro,Outcome=outcome))

ILAALASSObs <- predictionStats_regression(ILAALASSOcv$medianTest,"ILLA-LASSO: CV")
```

### ENET 

```{r ENET, results = "asis", warning = FALSE, dpi=300, fig.height= 4.5, fig.width= 6.0}

ENETcv <- randomCV(fittingFunction = GLMNET_ELASTICNET_MIN,
                     trainSampleSets = PLScv$trainSamplesSets)
ENETbs <- predictionStats_regression(ENETcv$medianTest,"ENET: CV")

```

### ILAAA ENET 

```{r ILAAENET, results = "asis", warning = FALSE, dpi=300, fig.height= 4.5, fig.width= 6.0}


ILAAENETcv <- randomCV(fittingFunction = filteredFit,
                     trainSampleSets = PLScv$trainSamplesSets,
                     fitmethod = GLMNET_ELASTICNET_MIN,
                      filtermethod = NULL,
                    DECOR = TRUE,
                    DECOR.control=list(thr=thro,Outcome=outcome))

ILAAENETbs <- predictionStats_regression(ILAAENETcv$medianTest,"ILLA-ENET: CV")

```


## The Reports
```{r tables, results = "asis", warning = FALSE,  dpi=300, fig.height= 4.5, fig.width= 6.0}
par(op)
RMSTABLE <- rbind(
                  PLSbs$RMSEci,
                  PCbs$RMSEci,
#                  CPPlbs$RMSEci,
                  LASSObs$RMSEci,
                  PCALASSObs$RMSEci,
                  ILAALASSObs$RMSEci,
                  ENETbs$RMSEci,
                  ILAAENETbs$RMSEci
                  )
colnames(RMSTABLE) <- c("Median","Lower","Upper")
#rownames(RMSTABLE) <- c("PLSR","PCR","CPP",
#                        "LASSO","PCA-LASSO","ILAA-LASSO","ENET","ILAA-ENET")

rownames(RMSTABLE) <- c("PLSR","PCR",
                        "LASSO","PCA-LASSO","ILAA-LASSO",
                        "ENET","ILAA-ENET")

pander::pander(RMSTABLE)

themethod <- rownames(RMSTABLE)
thesets <- c("Fit Method")
pRMS <- barPlotCiError(RMSTABLE,
               "RMS", 
               thesets=thesets, 
               themethod=themethod, 
               main="RMS",
               angle=0, 
               offsets=c(0.1,1.0),
               scoreDirection="<",args.legend=list(x="bottomleft"),
               col=rainbow(length(themethod)))

par(op)


MADTABLE <- rbind(
                  PLSbs$MAEci,
                  PCbs$MAEci,
#                  CPPlbs$MAEci,
                  LASSObs$MAEci,
                  PCALASSObs$MAEci,
                  ILAALASSObs$MAEci,
                  ENETbs$MAEci,
                  ILAAENETbs$MAEci
                  )


colnames(MADTABLE) <- colnames(RMSTABLE)
rownames(MADTABLE) <- rownames(RMSTABLE)

pander::pander(MADTABLE)


pber <- barPlotCiError(MADTABLE,
               "MAD", 
               thesets=thesets, 
               themethod=themethod, 
               main="Mean Absolute DIfferences",
               angle=0, 
               offsets=c(0.1,0.5),
               scoreDirection="<",args.legend=list(x="bottomright"),
               col=rainbow(length(themethod))
               )

PearsonTABLE <- rbind(
                  PLSbs$corci,
                  PCbs$corci,
#                  CPPlbs$corci,
                  LASSObs$corci,
                  PCALASSObs$corci,
                  ILAALASSObs$corci,
                  ENETbs$corci,
                  ILAAENETbs$corci
                  )


colnames(PearsonTABLE) <- colnames(RMSTABLE)
rownames(PearsonTABLE) <- rownames(RMSTABLE)

pander::pander(PearsonTABLE)


pber <- barPlotCiError(PearsonTABLE,
               "Pearson Correlation", 
               thesets=thesets, 
               themethod=themethod, 
               main="Pearson Correlation",
               angle=0, 
               offsets=c(0.1,0.5),
               scoreDirection=">",args.legend=list(x="bottomright"),
               col=rainbow(length(themethod))
               )


```

### Saving ALL

```{r}
save.image(paste("SOTACV_analyiss",studyName,".RData",sep="_"))
```
