---
title: "Decorrelation-Based Feature Discovery: GI"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")

```

# Effect of UPSTM-Based Decorrelation on Feature Discovery



### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
library(umap)
library(tsne)
library(entropy)

op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)
source("C:/Users/jtame/Documents/GitHub/LatentBiomarkers/RMD/DecorrelationCV.R")

```



## The Data


```{r}

dataGI <- as.data.frame(read_excel("~/GitHub/LatentBiomarkers/Data/GI/data.xlsx", sheet = "Sheet1"))
dataGI$ID <- NULL

table(dataGI$V2)
dataSet1 <- subset(dataGI,V2==1)
class <- dataSet1$V1
dataSet1$V1 <- NULL
dataSet1$V2 <- NULL
colnames(dataSet1) <- paste(colnames(dataSet1),"WL",sep="_")
dataSet2 <- subset(dataGI,V2==2)
dataSet2$V1 <- NULL
dataSet2$V2 <- NULL
colnames(dataSet2) <- paste(colnames(dataSet2),"NBI",sep="_")
dataGI <- cbind(dataSet1,dataSet2)
dataGI$class <- 1*(class > 1)
table(dataGI$class)

```
#### Standarize the names for the reporting

```{r results = "asis"}
studyName <- "GI"
dataframe <- dataGI
outcome <- "class"

nLoops <- 100

needScaling <- TRUE
IDSample <- FALSE
thro <- 0.8
```
## CV Analysis and report

```{r parent, child = here::here("~/GitHub/LatentBiomarkers/RMD/Child_univariate/CV_analysis.Rmd")}
```


## Testing different parameters
```{r}

cvData_0.9 <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.9)
cvData_0.8 <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.8)
cvData_0.7 <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.7)
cvData_0.6 <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.6)
cvData_0.5 <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.5)
bpDe <- predictionStats_binary(cvData_0.9$DeMedTestRaw,"IDeA@0.9")
bpDe <- predictionStats_binary(cvData_0.8$DeMedTestRaw,"IDeA@0.8")
bpDe <- predictionStats_binary(cvData_0.7$DeMedTestRaw,"IDeA@0.7")
bpDe <- predictionStats_binary(cvData_0.6$DeMedTestRaw,"IDeA@0.6")
bpDe <- predictionStats_binary(cvData_0.5$DeMedTestRaw,"IDeA@0.5")

cvData_0.9_R <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.9,corRank=TRUE)
cvData_0.8_R <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.8,corRank=TRUE)
cvData_0.7_R <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.7,corRank=TRUE)
cvData_0.6_R <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.6,corRank=TRUE)
cvData_0.5_R <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.5,corRank=TRUE)
bpDe <- predictionStats_binary(cvData_0.9_R$DeMedTestRaw,"IDeA@0.9 CorRank")
bpDe <- predictionStats_binary(cvData_0.8_R$DeMedTestRaw,"IDeA@0.8 CorRank")
bpDe <- predictionStats_binary(cvData_0.7_R$DeMedTestRaw,"IDeA@0.7 CorRank")
bpDe <- predictionStats_binary(cvData_0.6_R$DeMedTestRaw,"IDeA@0.6 CorRank")
bpDe <- predictionStats_binary(cvData_0.5_R$DeMedTestRaw,"IDeA@0.5 CorRank")


cvData_0.9_D <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.9,Outcome=outcome)
cvData_0.8_D <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.8,Outcome=outcome)
cvData_0.7_D <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.7,Outcome=outcome)
cvData_0.6_D <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.6,Outcome=outcome)
cvData_0.5_D <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.5,Outcome=outcome)
bpDe <- predictionStats_binary(cvData_0.9_D$DeMedTestRaw,"IDeA@0.9 Driven")
bpDe <- predictionStats_binary(cvData_0.8_D$DeMedTestRaw,"IDeA@0.8 Driven")
bpDe <- predictionStats_binary(cvData_0.7_D$DeMedTestRaw,"IDeA@0.7 Driven")
bpDe <- predictionStats_binary(cvData_0.6_D$DeMedTestRaw,"IDeA@0.6 Driven")
bpDe <- predictionStats_binary(cvData_0.5_D$DeMedTestRaw,"IDeA@0.5 Driven")

cvData_0.9_S <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.9,method="spearman")
cvData_0.8_S <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.8,method="spearman")
cvData_0.7_S <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.7,method="spearman")
cvData_0.6_S <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.6,method="spearman")
cvData_0.5_S <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,DecorPCAEFA=FALSE,thr=0.5,method="spearman")
bpDe <- predictionStats_binary(cvData_0.9_S$DeMedTestRaw,"IDeA@0.9 Spearman")
bpDe <- predictionStats_binary(cvData_0.8_S$DeMedTestRaw,"IDeA@0.8 Spearman")
bpDe <- predictionStats_binary(cvData_0.7_S$DeMedTestRaw,"IDeA@0.7 Spearman")
bpDe <- predictionStats_binary(cvData_0.6_S$DeMedTestRaw,"IDeA@0.6 Spearman")
bpDe <- predictionStats_binary(cvData_0.5_S$DeMedTestRaw,"IDeA@0.5 Spearman")

cvData_0.9_S_D <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,
                         DecorPCAEFA=FALSE,thr=0.9,Outcome=outcome,method="spearman")
cvData_0.8_S_D <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,
                         DecorPCAEFA=FALSE,thr=0.8,Outcome=outcome,method="spearman")
cvData_0.7_S_D <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,
                         DecorPCAEFA=FALSE,thr=0.7,Outcome=outcome,method="spearman")
cvData_0.6_S_D <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,
                         DecorPCAEFA=FALSE,thr=0.6,Outcome=outcome,method="spearman")
cvData_0.5_S_D <- CV_TDR(dataframe,outcome,loops=nLoops,IDSample=IDSample,scale=FALSE,
                         DecorPCAEFA=FALSE,thr=0.5,Outcome=outcome,method="spearman")
bpDe <- predictionStats_binary(cvData_0.9_S_D$DeMedTestRaw,"IDeA@0.9 Spearman Driven")
bpDe <- predictionStats_binary(cvData_0.8_S_D$DeMedTestRaw,"IDeA@0.8 Spearman Driven")
bpDe <- predictionStats_binary(cvData_0.7_S_D$DeMedTestRaw,"IDeA@0.7 Spearman Driven")
bpDe <- predictionStats_binary(cvData_0.6_S_D$DeMedTestRaw,"IDeA@0.6 Spearman Driven")
bpDe <- predictionStats_binary(cvData_0.5_S_D$DeMedTestRaw,"IDeA@0.5 Spearman Driven")


save.image(paste("ALLCV_analyiss",studyName,".RData",sep="_"))

```

