---
title: "SOTA: Saliva COVID-19"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")

```

# Effect of UPSTM-Based Decorrelation on ML Performance


### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
library(umap)
library(tsne)
library(entropy)
library(pls)

op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```


## Material and Methods


## Data: The YArn Data-Set

The data to process is described in the PLS package 



IR YARN Dataset




I added a column to the data identifying the repeated experiments.

```{r}
data(gasoline)

Gasoline <- as.data.frame(cbind(gasoline$NIR,Octane=gasoline$octane))
colnames(Gasoline) <- str_remove_all(colnames(Gasoline)," ")
colnames(Gasoline) <- paste("V",colnames(Gasoline),sep="")
```

#### Standarize the names for the reporting

```{r results = "asis"}
studyName <- "gasoline"
dataframe <- Gasoline
outcome <- "VOctane"

thro <- 0.8

cexheat <- 0.35
loops <- 100

tfrac <- 0.80



```

## Generaring the report

```{r parent, child = here::here("~/GitHub/LatentBiomarkers/RMD/Child_univariate/child_SOTA_regression.Rmd")}
```
