---
title: "SOTA: Saliva COVID-19"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")

```

# Effect of UPSTM-Based Decorrelation on ML Performance


### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
library(umap)
library(tsne)
library(entropy)
library(pls)

op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```


## Material and Methods


## Data: The YArn Data-Set

The data to process is described in the PLS package 



IR YARN Dataset




I added a column to the data identifying the repeated experiments.

```{r}
data(yarn)

YARN <- rbind(t(yarn$NIR),density=yarn$density)
```

#### Standarize the names for the reporting

```{r results = "asis"}
studyName <- "YARN"
dataframe <- SalivaIR_Avg
outcome <- "class"
tfrac <- 0.80
nLoops <- 50
needScaling <- FALSE
IDSample <- FALSE
thro <- 0.8

#mvs <- multivariate_BinEnsemble(dataframe,outcome)
#st <- ILAA(dataframe)
#mvs <- multivariate_BinEnsemble(st,outcome)

#bmo <- BSWiMS.model(class~.,dataframe,print=TRUE,loops=1,elimination.bootstrap.steps=0)
#bmo$formula.list

yarn.pls <- plsr(density ~ NIR, 6, data = yarn, validation = "CV")

plscf <- yarn.pls$coefficients
yarn.pls$loadings


```
## CV Analysis and report

```{r parent, child = here::here("~/GitHub/LatentBiomarkers/RMD/Child_univariate/SOTACV_analysis.Rmd")}
```
