---
title: "Decorrelation-Based Feature Discovery: NHNES"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")

```


# Effect of UPSTM-Based Decorrelation on Feature Discovery


### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
library(umap)
library(tsne)
library(entropy)

op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```


## Material and Methods


## The Data

Data source:

https://www.kaggle.com/datasets/cdc/national-health-and-nutrition-examination-survey?select=labs.csv


Details:

https://www.cdc.gov/Nchs/Nhanes/about_nhanes.htm



```{r}
demographic <- as.data.frame(read_excel("~/GitHub/LatentBiomarkers/Data/NHNES/demographic.xlsx"))
demographiDesc <- as.data.frame(read_excel("~/GitHub/LatentBiomarkers/Data/NHNES/demographic.xlsx",sheet = "Sheet1"))

rownames(demographic) <- demographic$SEQN
demographic$SEQN <- NULL

vartokeep <- demographiDesc[demographiDesc$Keep=="Yes",1]
demographic <- demographic[,vartokeep]

keepColumn <- apply(!is.na(demographic),2,sum)/nrow(demographic) > 0.75
demographic <- demographic[,keepColumn]
demographic <- demographic[complete.cases(demographic),]

## Examination data
examination <- as.data.frame(read_excel("~/GitHub/LatentBiomarkers/Data/NHNES/examination.xlsx"))
examinationDesc <- as.data.frame(read_excel("~/GitHub/LatentBiomarkers/Data/NHNES/examination.xlsx",sheet = "Sheet1"))
rownames(examination) <- examination$SEQN
examination$SEQN <- NULL

bpresDI <- examination[,c("BPXDI1","BPXDI2","BPXDI3","BPXDI4")]
examination[,c("BPXDI1","BPXDI2","BPXDI3","BPXDI4")] <- NULL
bpresDIM <- apply(bpresDI,1,mean,na.rm=TRUE)
summary(bpresDIM)

bpresSY <- examination[,c("BPXSY1","BPXSY2","BPXSY3","BPXSY4")]
examination[,c("BPXSY1","BPXSY2","BPXSY3","BPXSY4")] <- NULL
bpresSYM <- apply(bpresSY,1,mean,na.rm=TRUE)
summary(bpresSYM)

examination$PEASCST1 <- NULL
examination$bpresDIM <- bpresDIM
examination$bpresSYM <- bpresSYM
  
keepColumn <- apply(!is.na(examination),2,sum)/nrow(examination) > 0.75
examination <- examination[,keepColumn]
keepColumnVar <- !is.na(apply(examination,2,var,na.rm = TRUE))
examination <- examination[,keepColumnVar]
examination <- examination[complete.cases(examination),]
examination <- examination[examination$bpresDIM>0,]



## questionnaire data
questionnaire <- as.data.frame(read_excel("~/GitHub/LatentBiomarkers/Data/NHNES/questionnaire.xlsx"))
questionnaireDesc <- as.data.frame(read_excel("~/GitHub/LatentBiomarkers/Data/NHNES/questionnaire.xlsx",sheet = "Sheet1"))
rownames(questionnaire) <- questionnaire$SEQN
questionnaire$SEQN <- NULL
table(questionnaire$MCQ010)

#keepColumn <- apply(!is.na(questionnaire),2,sum)/nrow(questionnaire) > 0.85
#questionnaire <- questionnaire[,keepColumn]
#keepColumnVar <- !is.na(apply(questionnaire,2,var,na.rm = TRUE))
#questionnaire <- questionnaire[,keepColumnVar]
#questionnaire <- questionnaire[complete.cases(questionnaire),]
#keeprow <- apply(questionnaire,2,max) < 9000
#questionnaire <- questionnaire[keeprow,]
#table(questionnaire$MCQ010)

## Diabetes
Diabetes <- questionnaire$MCQ010
names(Diabetes) <- rownames(questionnaire) 
Diabetes <- Diabetes[!is.na(Diabetes)]
Diabetes <- Diabetes[Diabetes<3]
table(Diabetes)

## Depression 
depression <- questionnaire[,c("DPQ010","DPQ020","DPQ030","DPQ040","DPQ050","DPQ060","DPQ070","DPQ080","DPQ090")]
depression[depression>5] <- "NA"
depressionTot <- apply(depression>0,1,sum,na.rm=TRUE) > 0
donnow <- apply(is.na(depression),1,sum) == 9
table(depressionTot)
depressionTot <- depressionTot[!donnow]
table(depressionTot)

## The labs data
labs <- as.data.frame(read_excel("~/GitHub/LatentBiomarkers/Data/NHNES/labs.xlsx"))
labsDesc <- as.data.frame(read_excel("~/GitHub/LatentBiomarkers/Data/NHNES/labs.xlsx",sheet = "Sheet1"))

rownames(labs) <- labs$SEQN
labs$SEQN <- NULL

keepColumn <- apply(!is.na(labs),2,sum)/nrow(labs) > 0.75
labs <- labs[,keepColumn]
keepColumnVar <- !is.na(apply(labs,2,var,na.rm = TRUE))
labs <- labs[,keepColumnVar]
labs <- labs[complete.cases(labs),]

includeIDS <- rownames(labs)[rownames(labs) %in% rownames(examination)]
includeIDS <- includeIDS[includeIDS %in% rownames(demographic)]

includeIDS <- includeIDS[includeIDS %in% names(Diabetes)]

Diab <- Diabetes[includeIDS]
table(Diab)

NHNES <- cbind(demographic[includeIDS,],examination[includeIDS,],labs[includeIDS,]) 
NHNES$Diab <- Diab

table(NHNES$Diab)

NHNES <- NHNES[NHNES$RIDAGEYR >= 20,]

NHNES$Diab <- 1*(NHNES$Diab == 1)

table(NHNES$Diab)
includeIDS <- rownames(NHNES)
includeIDS <- includeIDS[includeIDS %in% names(depressionTot)]
depressionTot <- depressionTot[includeIDS]
NHNESDep <- cbind(NHNES[includeIDS,],depressionTot)

NHNESDep$depressionTot <- 1*NHNESDep$depressionTot

tbdep <- table(NHNESDep$depressionTot)
genderDiab <- NHNESDep[,c("RIAGENDR","Diab","depressionTot")]

isContinuous <- sapply(apply(NHNESDep,2,unique),length) > 4
sum(isContinuous)

NHNESDep <- cbind(NHNESDep[,isContinuous],genderDiab)

table(NHNESDep$depressionTot)
  
```
#### Standarize the names for the reporting

```{r results = "asis"}
studyName <- "NHNES"
dataframe <- NHNESDep
outcome <- "depressionTot"

TopVariables <- 10

thro <- 0.40
cexheat = 0.15

```

## Generaring the report

```{r parent, child = here::here("~/GitHub/LatentBiomarkers/RMD/Child_univariate/child_Simple_LatentBiomarkers.Rmd")}
```

## The Latent formulas

```{r}
theLaFormulas <- getLatentCoefficients(DEdataframe)
                       

## Add the variable description

allvardes <- rbind(demographiDesc[,1:2],examinationDesc[,1:2],labsDesc[,1:2])
dup <- duplicated(allvardes[,1])
allvardes <- allvardes[!dup,]
rownames(allvardes) <- allvardes[,1]
lavar <-  names(theLaFormulas)[1]
theLaFormulas[[lavar]]
for (lavar in names(theLaFormulas))
{
  theLaFormulas[[lavar]]$Desc <- paste("(",allvardes[names(theLaFormulas[[lavar]]),2],")\n\r",sep="")
}

pander::pander(theLaFormulas)

```

