---
title: "Decorrelation-Based Feature Discovery: Gasoline"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")

```

# Effect of UPSTM-Based Decorrelation on Feature Discovery


### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
library(umap)
library(tsne)
library(entropy)
library(pls)
op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)
source("C:/Users/jtame/Documents/GitHub/LatentBiomarkers/RMD/DecorrelationCV.R")

```


## Material and Methods

About Dataset
From the PLS package Gasoline

## The Data

gasoline

```{r}

data(gasoline)
gasdata <- as.data.frame(cbind(octane=gasoline$octane,as.matrix(gasoline$NIR)))
gasdata$octane <- 1.0*(gasdata$octane > median(gasdata$octane))
colnames(gasdata) <- str_replace_all(colnames(gasdata)," ","")
colnames(gasdata) <- paste("V",colnames(gasdata),sep="")
table(gasdata$Voctane)

```

#### Standarize the names for the reporting

```{r results = "asis"}
studyName <- "gasoline"
dataframe <- gasdata
outcome <- "Voctane"

needScaling <- TRUE
nLoops <- 100

IDSample <- FALSE
thro <- 0.8
#cmethod="spearman"

```
## CV Analysis and report

```{r parent, child = here::here("~/GitHub/LatentBiomarkers/RMD/Child_univariate/CV_analysis.Rmd")}
```

