---
title: "Decorrelation-Based Feature Discovery: Activity-Whole"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")

```


# Effect of UPSTM-Based Decorrelation on Feature Discovery


### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
library(umap)
library(tsne)
library(entropy)

op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```

## Material and Methods

Data Source 
https://www.kaggle.com/datasets/sooyoungher/smoking-drinking-dataset



## The Data

```{r}
S_D_data <- read.csv("~/GitHub/LatentBiomarkers/Data/smoking_driking_dataset_Ver01.csv", header=TRUE, stringsAsFactors=TRUE)
S_D_data_R <- S_D_data[1:2000,]
table(S_D_data_R$DRK_YN)
S_D_data_R$DRK_YN <- 1*(S_D_data_R$DRK_YN=="Y")
S_D_data_R$SMK_stat_type_cd <- NULL
S_D_data_R[,1:ncol(S_D_data_R)] <- sapply(S_D_data_R,as.numeric)
summary(S_D_data_R)
```


#### Standarize the names for the reporting

```{r results = "asis"}
studyName <- "Drink"
dataframe <- S_D_data_R
outcome <- "DRK_YN"

TopVariables <- 5
thro <- 0.40
cexheat = 0.15


```


## Generaring the report

```{r parent, child = here::here("~/GitHub/LatentBiomarkers/RMD/Child_univariate/child_Simple_LatentBiomarkers.Rmd")}
```