---
title: "Decorrelation-Based Class Discovery: Prostate"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")

```


# Effect of UPSTM-Based Decorrelation on Feature Discovery


### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
library(umap)
library(tsne)
library(entropy)

op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```


## Material and Methods





## The Data


```{r}

Prostate_DS <- read.csv("~/GitHub/LatentBiomarkers/Data/Prostate_GSE6919_U95B.csv")
colnames(Prostate_DS) <-str_replace_all(colnames(Prostate_DS),"\\.","_")
rownames(Prostate_DS) <- Prostate_DS$samples
Prostate_DS$samples <- NULL
table(Prostate_DS$type)
#Prostate_DS$type <- 1*(Prostate_DS$type == "primary_prostate_tumor")
table(Prostate_DS$type)

```

#### Standarize the names for the reporting

```{r results = "asis"}
studyName <- "Prostate"

classType <- Prostate_DS$type
names(classType) <- rownames(Prostate_DS)
Prostate_DS$type <- NULL
dataframe <- as.data.frame(t(Prostate_DS))
thro <- 0.4
cexheat = 0.15
TopVariables <- 10

```


## Generaring the report

```{r parent, child = here::here("~/GitHub/LatentBiomarkers/RMD/Child_univariate/child_Simple_LatentClass.Rmd")}
```