---
title: "Decorrelation-Based Feature Discovery: Saliva COVID-19"
author: "Jose Tamez"
date: "2022-10-02"
output:
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")

```

# Effect of UPSTM-Based Decorrelation on Feature Discovery


### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
library(umap)
library(tsne)
library(entropy)

op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)
source("C:/Users/jtame/Documents/GitHub/LatentBiomarkers/RMD/DecorrelationCV.R")

```


## Material and Methods


## Data: The COVID_19 Data-Set

The data to process is described in:

<https://zenodo.org/record/4156647#.Y1bSF3bMKUk>


IR Saliva Testing Dataset


10.5281/zenodo.4156647
<https://doi.org/10.5281/zenodo.4156647>


I added a column to the data identifying the repeated experiments.

```{r}

SalivaIR <- as.data.frame(read_excel("~/GitHub/FCA/Data/SalivaThermal_Source_Data_2.xlsx"))


SalivaIR_set1 <- subset(SalivaIR,RepID==1)
rownames(SalivaIR_set1) <- SalivaIR_set1$ID
SalivaIR_set1$RepID <- NULL
SalivaIR_set1$ID <- NULL
SalivaIR_set1$Ct <- NULL

SalivaIR_set2 <- subset(SalivaIR,RepID==2)
rownames(SalivaIR_set2) <- SalivaIR_set2$ID
SalivaIR_set2$RepID <- NULL
SalivaIR_set2$ID <- NULL
SalivaIR_set2$Ct <- NULL

SalivaIR_set3 <- subset(SalivaIR,RepID==3)
rownames(SalivaIR_set3) <- SalivaIR_set3$ID
SalivaIR_set3$RepID <- NULL
SalivaIR_set3$ID <- NULL
SalivaIR_set3$Ct <- NULL

SalivaIR_Avg <- (SalivaIR_set1 + SalivaIR_set2 + SalivaIR_set3)/3


colnames(SalivaIR_Avg) <- paste("V",colnames(SalivaIR_Avg),sep="_")

SalivaIR_Avg$class <- 1*(str_detect(rownames(SalivaIR_Avg),"P"))

pander::pander(table(SalivaIR_Avg$class))

```

#### Standarize the names for the reporting

```{r results = "asis"}
studyName <- "SalivaCOVID19"
dataframe <- SalivaIR_Avg
outcome <- "class"


```

### CV feature Selection
```{r results = "asis", warning = FALSE, dpi=300, fig.height= 6.0, fig.width= 8.0}

cvDataFS <- CV_TDR(dataframe,outcome,loops=100,scale=FALSE,thr=0.8)

```

### Report
```{r results = "asis", warning = FALSE, dpi=300, fig.height= 6.0, fig.width= 8.0}

lassSFRaw <- as.numeric(unlist(lapply(cvDataFS$SelectedLASSOFeatures,length)))
lassSFDe <- as.numeric(unlist(lapply(cvDataFS$DeSelectedLASSOFeatures,length)))
FSRaw <- as.numeric(unlist(lapply(cvDataFS$SelectedTrainFeatures,length)))
FSDe <- as.numeric(unlist(lapply(cvDataFS$DeSelectedTrainFeatures,length)))
boxplot(cbind(RAW=cvDataFS$TDR,IDeA=cvDataFS$DeTDR),notch=TRUE,main="TDR")
boxplot(cbind(RAW=cvDataFS$ROCAUC,IDeA=cvDataFS$DeROCAUC),notch=TRUE,main="ROC AUC")
boxplot(cbind(RAW=cvDataFS$topROCAUC,IDeA=cvDataFS$DetopROCAUC),notch=TRUE,main="Top Feature: ROC AUC")
boxplot(cbind(RAW=FSRaw,IDeA=FSDe),main="Number of Selected Features")
boxplot(cbind(RAW=lassSFRaw,IDeA=lassSFDe),main="Number of Selected Features by LASSO Min")
boxplot(cbind(Filter=cvDataFS$DeFraction,LASSO=cvDataFS$DeFractionLasso),main="Fraction of Latent Variables")

bpRaw <- predictionStats_binary(cvDataFS$medTestRaw,"Raw")
bpDe <- predictionStats_binary(cvDataFS$DeMedTestRaw,"IDeA")
bpPCA <- predictionStats_binary(cvDataFS$PCAMedTestRaw,"PCA")


pander::pander(apply(cvDataFS$datadim,2,mean),caption="Data Dimensions")

```


### Summary
```{r results = "asis"}
TDR_raw <- c(mean=mean(cvDataFS$TDR),sd=sd(cvDataFS$TDR))
TDR_de <- c(mean=mean(cvDataFS$DeTDR),sd=sd(cvDataFS$DeTDR))
ROCAUC_raw <- c(mean=mean(cvDataFS$ROCAUC),sd=sd(cvDataFS$ROCAUC))
TOPROCAUC_raw <- c(mean=mean(cvDataFS$topROCAUC),sd=sd(cvDataFS$topROCAUC))
ROCAUC_de <- c(mean=mean(cvDataFS$DeROCAUC),sd=sd(cvDataFS$DeROCAUC))
TOPROCAUC_de <- c(mean=mean(cvDataFS$DetopROCAUC),sd=sd(cvDataFS$DetopROCAUC))
SelectedFeaturesRaw <- c(mean=mean(FSRaw),sd=sd(FSRaw))
SelectedFeaturesDe <- c(mean=mean(FSDe),sd=sd(FSDe))
SelectedFeaturesLassoRaw <- c(mean=mean(lassSFRaw),sd=sd(lassSFRaw))
SelectedFeaturesLassoDe <- c(mean=mean(lassSFDe),sd=sd(lassSFDe))
FractionOfLatent <- c(mean=mean(cvDataFS$DeFraction),sd=sd(cvDataFS$DeFraction))
FractionOfLassoLatent <- c(mean=mean(cvDataFS$DeFractionLasso),sd=sd(cvDataFS$DeFractionLasso))
latVarSize <- c(mean=mean(cvDataFS$Avlen),sd=sd(cvDataFS$Avlen))
NumLatVar <- c(mean=mean(cvDataFS$NumLatent),sd=sd(cvDataFS$NumLatent))
NumLofCorrelated <- c(mean=mean(cvDataFS$totCorrelated),sd=sd(cvDataFS$totCorrelated))

SummaryRaw <- rbind(TDR_raw,
                 ROCAUC_raw,
                 TOPROCAUC_raw,
                 SelectedFeaturesRaw,
                 SelectedFeaturesLassoRaw
                 )
                
pander::pander(SummaryRaw)                 

diffinROCACU <- cvDataFS$DeROCAUC-cvDataFS$ROCAUC
DifFROCAUC <- c(mean=mean(diffinROCACU),sd=sd(diffinROCACU))
diffinTOPROCACU <- cvDataFS$DetopROCAUC-cvDataFS$topROCAUC
DifTopROCAUC <- c(mean=mean(diffinTOPROCACU),sd=sd(diffinTOPROCACU))
SummaryDe <- rbind(TDR_de,
                 ROCAUC_de,
                 TOPROCAUC_de,
                 SelectedFeaturesDe,
                 SelectedFeaturesLassoDe,
                 FractionOfLatent,
                 FractionOfLassoLatent,
                 DifFROCAUC,
                 DifTopROCAUC,
                 NumLatVar,
                 latVarSize,
                 NumLofCorrelated
                 )

pander::pander(SummaryDe)
pander::pander(c(pvalue=pnorm(0, mean(diffinROCACU), sd(diffinROCACU))),caption="ROC Diff, p.value")
pander::pander(summary(as.numeric(unlist(cvDataFS$rocTest))),caption="ROC p.values")

pander::pander(c(pvalue=pnorm(0, mean(diffinTOPROCACU), sd(diffinTOPROCACU))),caption="TOP ROC Diff, p.value")

pander::pander(roc.test(bpRaw$ROC.analysis$roc.predictor,bpDe$ROC.analysis$roc.predictor))


```

### Saving ALL

```{r}
save.image(paste("CV_analyiss",studyName,".RData",sep="_"))

```

